新增詳細的安裝及配置方法
Moemu/Muice-Chatbot pull request #6
Opened 2023-09-09 15:06 UTC by TurboHK

目前僅有 Windows 版本

2023-09-09 17:05 UTC, Moemu requested changes
作為在大陸發佈的項目，我不建議您將`readme.md`直接翻譯為繁體中文，若要提供翻譯服務，還請將更改移至`readme_zh-tw.md`

2023-09-09 17:08 UTC, Moemu commented
另外，其實本項目編寫時是在CentOS進行調試處理，對Windows的兼容性，本人不敢妄下論斷

2023-09-09 18:02 UTC, TurboHK commented
> 作為在大陸發佈的項目，我不建議您將`readme.md`直接翻譯為繁體中文，若要提供翻譯服務，還請將更改移至`readme_zh-tw.md`

如您所見，現在已更改為兩種中文變體分為兩個檔案儲存。

2023-09-09 18:31 UTC, Moemu approved these changes

2023-09-09 18:47 UTC, Moemu commented
已手動合併PR，感謝貢獻

2023-09-09 18:47 UTC, closed without merging

2023-09-11 14:26 UTC, TurboHK commented
> 另外，其實本項目編寫時是在CentOS進行調試處理，對Windows的兼容性，本人不敢妄下論斷

建議您將這一點放入 Readme 中，這將為其他使用者節省大量的時間